### ISSUE TITLE
Refactor Global Search

### ISSUE THREAD

**Issue by lucien-chastan** [lucien-chastan/oblyk#38]
Refactor the global search so that it finds all the elements without you needing to select a search type 

Possibility to filtered result after search

**Comment by mjamroz** [comment]
do you want to have direct search of database model by model (probably nice way to ddos ;) )or rather something like https://laravel.com/docs/5.7/scout / https://scotch.io/tutorials/build-search-functionality-with-laravel-scout-and-vue-js ?

**Comment by mjamroz** [comment]
hi,
sorry - about scout - i just read it need some external and paid xD service. then probably is a bad choice.
about java on your server, it seems strange, maybe you should consider moving to normal hosting provider? for example check this polish one:
https://www.mydevil.net/oferta.html
(1€ ~= 4zł)

and/or (but probably not good idea from your point of view) - since i've already account there, i could try to run elasticsearch and you could use it as a client from oblyk host. (it would be stupid because if user search @ oblyk it connect first to "my" mydevil, then mydevil ask oblyk db, then send back to oblyk (thru elasticsearch port). data transfer 3 times.

but if you dont care, i can set up something at my account.

**Comment by lucien-chastan** [comment]
I preferred not to have an dependency that I couldn't control...  
I don't know of any search engine that could work only with php
Do you have any idea ?

**Comment by lucien-chastan** [comment]
It could be fun!
at the moment I'm working on another very big [evolution](https://github.com/lucien-chastan/oblyk/tree/indoor_topo_and_sendlist)
It takes me all my development time on oblyk
I'm not sure when I'll have time to look at the research.
